---
swagger: "2.0.0"
info:
  description:
    "This is a sample server Petstore server.  You can find out more about\
    \ Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).\
    \  For this sample, you can use the api key `special-key` to test the authorization\
    \ filters."
  title: "Swagger Gym Api"
host: "89d0-213-109-80-222.ngrok-free.app"
schemes:
  - "https"
  - "http"
components:
  securitySchemes:
    Authorization:
      type: https
      scheme: bearer
      bearerFormat: JWT
      value: Bearer <JWT token here>
paths:
  /login:
    post:
      tags:
        - "user"
      summary: "User Login"
      operationId: "userLogin"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "loginData"
          description: "User login data"
          required: true
          schema:
            $ref: "#/definitions/LoginData"
      responses:
        200:
          description: "Login successful"
          schema:
            type: "object"
            properties:
              token:
                type: "string"
        401:
          description: "Unauthorized"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
  /register:
    post:
      tags:
        - "user"
      summary: "User Registration"
      operationId: "userRegistration"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "userData"
          description: "User registration data"
          required: true
          schema:
            $ref: "#/definitions/RegistrationData"
      responses:
        200:
          description: "Registration successful"
          schema:
            type: "object"
            properties:
              token:
                type: "string"
        400:
          description: "Bad Request"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
  /myTrainers:
    get:
      tags:
        - "user"
      summary: "Get My Trainers"
      operationId: "getMyTrainers"
      security:
        - Authorization: []
      responses:
        200:
          description: "List of trainers associated with the user's sessions"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Trainer"
        400:
          description: "Bad Request"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        404:
          description: "Visitor not found"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
        500:
          description: "Internal Server Error"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
definitions:
  RegistrationData:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
      name:
        type: "string"
      email:
        type: "string"
  LoginData:
    type: "object"
    properties:
      username:
        type: "string"
      password:
        type: "string"
  Trainer:
    type: "object"
    properties:
      _id:
        type: "string"
      name:
        type: "string"
  Session:
    type: "object"
    properties:
      _id:
        type: "string"
  CreateSessionData:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      date:
        type: "string"
        format: "date-time"
      maxVisitors:
        type: "integer"
  Visitor:
    type: "object"
    properties:
      _id:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
